/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


// libraries
#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"


int main(void)
{


	while(1)
	{
		toggle_pa5_led();
		delay();



	}



    return 0;


}




