/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>

#include "adc.h"
#include "gpio.h"
#include "stm_err.h"
#include "timer.h"
#include "uart.h"

int main(void)
{
    my_err_t uart_status = usart2_init();
    printf("USART2 init: %s\r\n", my_err_to_name(uart_status));

    adc1_pa0_single_polling_timed_init(5000U, &TIMER_2);

    while (1)
    {
        if (check_timer_flag(&TIMER_2) != 0U)
        {
            uint32_t raw_value = read_adc1_pa0_value();
            uint32_t voltage_integer_part =
                adc_to_voltage5V_integer_part(raw_value);
            uint32_t voltage_decimal_part =
                adc_to_voltage5V_decimal_part(raw_value);

            printf("ADC1 raw value: %lu\r\n", (unsigned long)raw_value);
            printf("ADC1 voltage: %lu.%03lu V\r\n",
                   (unsigned long)voltage_integer_part,
                   (unsigned long)voltage_decimal_part);

            delay();
            adc1_pa0_single_polling_timed_init(5000U, &TIMER_2);
        }
    }
}

