/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"
#include "uart.h"

static uint32_t previous_tim8_arr;
static volatile uint32_t adc2_raw_value;
static volatile uint8_t adc2_sample_ready;

static void update_led_from_potentiometer(void);

int main(void)
{
    my_err_t uart_status = usart2_init();
    printf("USART2 init: %s\r\n", my_err_to_name(uart_status));

    my_err_t pwm_status = tim_pwm_init(&TIM8_PWM);
    printf("TIM8 PWM init: %s\r\n", my_err_to_name(pwm_status));

    adc2_pa4_interrupt_continuous_init();
    __enable_irq();

    while (1)
    {
        update_led_from_potentiometer();
    }
}

void ADC_IRQHandler(void)
{
    if ((ADC2->SR & ADC_SR_EOC) != 0U)
    {
        adc2_raw_value = ADC2->DR;
        adc2_sample_ready = 1U;
    }
}

static void update_led_from_potentiometer(void)
{
    if (adc2_sample_ready == 0U)
    {
        return;
    }

    uint32_t raw_value = adc2_raw_value;
    adc2_sample_ready = 0U;

    uint32_t period = ((RCC->APB2ENR & RCC_APB2ENR_TIM8EN) != 0U)
                          ? TIM8->ARR
                          : previous_tim8_arr;
    uint32_t duty = (uint32_t)(((uint64_t)raw_value * period) / 4095U);

    if (duty < 18U)
    {
        if (TIM8->ARR != 0U)
        {
            previous_tim8_arr = TIM8->ARR;
        }

        RCC->APB2ENR &= ~RCC_APB2ENR_TIM8EN;

        for (volatile uint32_t i = 0; i < 4200U; i++)
        {
        }
    }
    else
    {
        RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;
        TIM8->CCR1 = duty;
    }
}



