/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "interrupt.h"
#include "pwm.h"
#include "stm_err.h"

#define MAX_BUFFER_RX_LEN 100U

static volatile char letters[MAX_BUFFER_RX_LEN];
static volatile uint8_t rx_index;
static volatile uint8_t tx_index;

static void set_led(uint8_t turn_on);

int main(void)
{
    usart2_interrupt_init();

    my_err_t pwm_status = tim_pwm_init(&TIM8_PWM);
    printf("TIM8 PWM init: %s\r\n", my_err_to_name(pwm_status));

    __enable_irq();

    uint8_t o_flag = 0U;
    uint8_t n_flag = 0U;
    uint8_t first_f_flag = 0U;
    uint8_t second_f_flag = 0U;

    printf("---------------------------------------------------------\r\n");
    printf("|  Type 'ON' and then press any key to turn the LED on  |\r\n");
    printf("| Type 'OFF' and then press any key to turn the LED off |\r\n");
    printf("---------------------------------------------------------\r\n");

    while (1)
    {
        if (tx_index != rx_index)
        {
            char current_char = letters[tx_index];

            if (current_char == '\r')
            {
                printf("\r\n");
            }
            else if ((o_flag == 1U) && (n_flag == 1U))
            {
                o_flag = 0U;
                n_flag = 0U;
                first_f_flag = 0U;
                second_f_flag = 0U;
                printf("%c", current_char);
                set_led(1U);
            }
            else if ((o_flag == 1U) &&
                     (first_f_flag == 1U) &&
                     (second_f_flag == 1U))
            {
                o_flag = 0U;
                n_flag = 0U;
                first_f_flag = 0U;
                second_f_flag = 0U;
                printf("%c", current_char);
                set_led(0U);
            }
            else if ((current_char == 'O') || (current_char == 'o'))
            {
                o_flag = 1U;
                n_flag = 0U;
                first_f_flag = 0U;
                second_f_flag = 0U;
                printf("%c", current_char);
            }
            else if (((current_char == 'N') || (current_char == 'n')) &&
                     (o_flag == 1U))
            {
                n_flag = 1U;
                first_f_flag = 0U;
                second_f_flag = 0U;
                printf("%c", current_char);
            }
            else if ((o_flag == 1U) &&
                     (first_f_flag == 0U) &&
                     ((current_char == 'F') || (current_char == 'f')))
            {
                first_f_flag = 1U;
                n_flag = 0U;
                second_f_flag = 0U;
                printf("%c", current_char);
            }
            else if ((o_flag == 1U) &&
                     (first_f_flag == 1U) &&
                     ((current_char == 'F') || (current_char == 'f')))
            {
                second_f_flag = 1U;
                n_flag = 0U;
                printf("%c", current_char);
            }
            else
            {
                printf("%c", current_char);
            }

            fflush(stdout);

            tx_index++;
            if (tx_index >= MAX_BUFFER_RX_LEN)
            {
                tx_index = 0U;
            }
        }
    }
}

void USART2_IRQHandler(void)
{
    if ((USART2->SR & USART_SR_RXNE) != 0U)
    {
        letters[rx_index] = (char)USART2->DR;

        rx_index++;
        if (rx_index >= MAX_BUFFER_RX_LEN)
        {
            rx_index = 0U;
        }
    }
}

static void set_led(uint8_t turn_on)
{
    pwm_set_tim8_duty_cycle((turn_on != 0U) ? TIM8->ARR : 0U);
}

