/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



// libraries
#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"

#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "adc.h"
#include "gpio.h"
#include "stm_err.h"
#include "uart.h"

static volatile uint32_t adc2_raw_value;
static volatile uint8_t adc2_sample_ready;

int main(void)
{
    my_err_t uart_status = usart2_init();
    printf("USART2 init: %s\r\n", my_err_to_name(uart_status));

    adc2_pa4_interrupt_continuous_init();
    __enable_irq();

    while (1)
    {
        if (adc2_sample_ready != 0U)
        {
            uint32_t raw_value = adc2_raw_value;
            adc2_sample_ready = 0U;

            delay();

            uint32_t voltage_integer_part =
                adc_to_voltage5V_integer_part(raw_value);
            uint32_t voltage_decimal_part =
                adc_to_voltage5V_decimal_part(raw_value);

            printf("ADC2 value: %lu\r\n", (unsigned long)raw_value);
            printf("ADC2 voltage: %lu.%03lu V\r\n",
                   (unsigned long)voltage_integer_part,
                   (unsigned long)voltage_decimal_part);
        }
    }
}

void ADC_IRQHandler(void)
{
    if ((ADC2->SR & ADC_SR_EOC) != 0U)
    {
        adc2_raw_value = ADC2->DR;
        adc2_sample_ready = 1U;
    }
}





