/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


// libraries
#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"

const char *USART_TAG = "USART2";

int main(void)
{

	my_err_t usart2_status = usart2_init();
	const char* usart_status_string = my_err_to_name(usart2_status);
	printf("%s : %s", USART_TAG, usart_status_string);


	while(1)
	{




	}



    return 0;


}
