/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



// libraries
#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"

// Macros
#define USART_RXNE				(1U<<5)
#define MAX_BUFFER_RX_LEN		(10)
#define ADCEOC					(1U<<1)



// Const tags
const char* TIM1_PWM_INIT_TAG   = "TIM1 PWM init";
const char* TIM8_PWM_INIT_TAG  = "TIM8 PWM init";
const char* USART2_INIT_TAG 	= "USART2 init";

// Force the compiler to check memory every time using volatile
volatile char letters[MAX_BUFFER_RX_LEN];
volatile uint8_t rx_index = 0;      // ISR uses this to write
volatile uint8_t tx_index = 0;      // Main loop uses this to read
volatile uint32_t adc2_raw_value = 0;
volatile uint8_t adc2_interrupt_flag = 0;
volatile uint32_t sampleCount = 0;




int main(void)
{



	my_err_t usart2_init_status = usart2_init();
	const char* usart2_init_char = my_err_to_name(usart2_init_status);
	printf("%s: %s\r\n", USART2_INIT_TAG, usart2_init_char);




	single_polling_adc1_pa0_init();



   uint32_t digitalValue = 0;
   uint32_t voltage_integer_part = 0;
   uint32_t voltage_decimal_part = 0;






	printf("Hello while-d world!\r\n");
	while(1)
	{



	    digitalValue = read_adc1_pa0_value();
	    printf("ADC1 value: %ld\r\n", digitalValue);

	    delay();

	    voltage_integer_part = adc_to_voltage5V_integer_part(digitalValue);
	    voltage_decimal_part = adc_to_voltage5V_decimal_part(digitalValue);
	    printf("ADC1 Voltage: %ld.%ld\r\n", voltage_integer_part, voltage_decimal_part);

	    uint32_t avgVoltage = adc1_pa0_avg_voltage(voltage_integer_part);
	    uint32_t numSamples = num_of_samples();

	    printf("Avg voltage: %ld\r\nNumber of Samples: %ld\r\n", avgVoltage, numSamples);


	}



    return 0;


}



void USART2_IRQHandler(void)
{
    // Check if the receive flag has been set
    if(USART2->SR & USART_RXNE)
    {
        // Read DR to clear the flag and store the byte
        letters[rx_index] = USART2->DR;

        // Advance write index and wrap around at 10
        rx_index++;
        if(rx_index >= MAX_BUFFER_RX_LEN)
        {
            rx_index = 0;
        }
    }
}

void ADC_IRQHandler(void)
{
	// Check if the end of conversion has been set
	if (ADC2->SR & ADCEOC)
	{
		// Read current digital voltage and clears EOC flag
		adc2_raw_value = ADC2->DR;

		// set flag that interrupt has occurred
		adc2_interrupt_flag = 1;

		sampleCount++;

	}
}



