/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "pwm.h"
#include "stm_err.h"
#include "uart.h"

static void pulse_led(void);

int main(void)
{
    my_err_t uart_status = usart2_init();
    printf("USART2 init: %s\r\n", my_err_to_name(uart_status));

    my_err_t pwm_status = tim_pwm_init(&TIM8_PWM);
    printf("TIM8 PWM init: %s\r\n", my_err_to_name(pwm_status));

    while (1)
    {
        pulse_led();
    }
}

static void pulse_led(void)
{
    uint32_t max_duty = TIM8->ARR;

    for (uint32_t duty = 0; duty <= max_duty; duty++)
    {
        pwm_set_tim8_duty_cycle((uint16_t)duty);
        printf("%lu\r\n", (unsigned long)duty);
    }

    for (uint32_t duty = max_duty; duty > 0U; duty--)
    {
        pwm_set_tim8_duty_cycle((uint16_t)duty);
        printf("%lu\r\n", (unsigned long)duty);
    }
}



