/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


// libraries
#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "pwm.h"
#include "stm_err.h"

const char* USART2_INIT_TAG = "USART2";


int main(void)
{

	pc13_user_button_exti_init();

	my_err_t usart2_init_status = usart2_init();
	const char* usart2_init_char = my_err_to_name(usart2_init_status);
	printf("%s: %s\r\n", USART2_INIT_TAG, usart2_init_char);

	// enable global interrupts
	__enable_irq();




	printf("Hello while-d world!\r\n");
	while(1)
	{}

    return 0;

}


void EXTI15_10_IRQHandler(void)
{
	// Check if the EXTI13 caused the interrupt
	if(EXTI->PR & EXTI_PR_PR13)
	{

		// Do something
		toggle_pa5_led();

		// Clear flag
		EXTI->PR = EXTI_PR_PR13;

	}

}





